# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-14 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='{{cookiecutter.model_name}}',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('{{cookiecutter.provider_name}}_id', models.TextField(unique=True)),
                ('event_title', models.TextField()),
                ('city_name', models.TextField(null=True)),
                ('city_code', models.TextField(null=True)),
                ('country_name', models.TextField(null=True)),
                ('country_code', models.TextField(null=True)),
                ('place_name', models.TextField()),
                ('place_latitude', models.FloatField(null=True)),
                ('place_longitude', models.FloatField(null=True)),
                ('can_sell', models.BooleanField(default=True)),
            ],
        ),
    ]
